language: node_js

node_js:
  - 10

cache:
  npm: true
  directories:
    - ~/.cache

install: npm install

before_install:
  - sudo apt-get install -y libgconf-2-4
addons:
  apt:
    update: true

before_script:
  # - npm audit
  - npm run lint
  # - npm run cy:verify

script: npm run build

after_script:
  - npm run serve -- &
  - npm run cy:run
  - kill $(jobs -p) || true

after_success:
  - npm run lh -- --perf=96 https://r3nya.ru

before_deploy:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile
  - greenkeeper-lockfile-update

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  local-dir: dist
  on:
    branch: develop
    tags: true

after_deploy: greenkeeper-lockfile-upload
